<?php

namespace XSolveSecurityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceRepository extends EntityRepository
 {

   public function saveResource(Resource $resource) {

      $em = $this->getEntityManager();
      $em->persist($resource);
      $em->flush();
   }

}
