<?php

namespace XSolveSecurityBundle\Entity;

use Doctrine\ORM\EntityRepository;
use XSolveSecurityBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

   public function saveUser(User $user) {
      $em = $this->getEntityManager();
      $em->persist($user);
      $em->flush();
   }

}
