<?php

namespace XSolveSecurityBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

   public function getAllUsersJson() {
     $users = $this->findAll();

      $tab = []; //tab contain id, usernames and passwords of all user in database
       foreach ($users as $user) {
	 $element = ['id' => $user->getId(), 'username' => $user->getUsername()];
	 $tab[] = $element;
      }
      $response = new JsonResponse();
      $response->setData($tab);

      return $response;
   }

}
