


security:
     firewalls:
         secured_area:
             pattern:    ^/
             anonymous: ~
             stateless: true
             simple_preauth:
               authenticator: apikey_authenticator
             provider: api_key_user_provider
     #        form_login:
     #            login_path:  login
     #            check_path:  login_check
     #        logout:
     #           path:   logout
     #           target: /
                
     access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }

     providers:
         api_key_user_provider:
            id: x_solve_security.xsolve_user_prvoider
       
     encoders:
         XSolveSecurityBundle\Entity\User: plaintext
         Symfony\Component\Security\Core\User\User: plaintext


