
security:
     firewalls:
         secured_area:
             pattern:    ^/
             anonymous: ~
             form_login:
                 login_path:  login
                 check_path:  login_check
             logout:
                path:   logout
                target: /
                
     access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }

     providers:
         main:
             entity: { class: XSolveSecurityBundle\Entity\User, property: username }
     encoders:
         XSolveSecurityBundle\Entity\User: plaintext
         Symfony\Component\Security\Core\User\User: plaintext